export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  summary: string;
  content: string;
  publishedAt: string;
  readingTime: string;
  tags: string[];
  coverImage?: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    slug: "why-i-love-frontend-development",
    title: "Why I Love Frontend Development",
    summary: "Exploring the creative and technical aspects of frontend development that make it so engaging.",
    content: `
## The Intersection of Art and Logic

Frontend development is a unique field where creativity meets engineering. Unlike backend development, where the focus is often on data processing and server logic, frontend allows you to see the immediate visual impact of your code.

### Instant Feedback Loop

One of the most satisfying things about frontend dev is the instant feedback loop. You change a CSS property, save the file, and boom—the button is now blue. This immediacy encourages experimentation and rapid iteration.

### The User Experience

At the end of the day, the frontend is what the user interacts with. No matter how powerful the backend is, if the frontend is clunky or unresponsive, the user experience suffers. Building smooth, accessible, and beautiful interfaces is a responsibility I take seriously.

## Modern Tools

The ecosystem is constantly evolving. From React and Next.js to Tailwind CSS and Framer Motion, the tools we have today enable us to build things that were impossible just a few years ago.

### Conclusion

Frontend development is not just about making things look pretty; it's about creating intuitive, performant, and accessible experiences for users. That's why I love it.
    `,
    publishedAt: "2025-10-15",
    readingTime: "3 min read",
    tags: ["Frontend", "Web Development", "Personal"],
    coverImage: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "2",
    slug: "mastering-react-hooks",
    title: "Mastering React Hooks",
    summary: "A deep dive into useEffect, useState, and custom hooks for cleaner React code.",
    content: `
## Introduction to Hooks

React Hooks revolutionized how we write components. They allow us to use state and other React features without writing a class. But mastering them takes practice.

### The Power of useEffect

\`useEffect\` is arguably the most powerful and tricky hook. It handles side effects like data fetching, subscriptions, and manually changing the DOM.

\`\`\`tsx
useEffect(() => {
  const fetchData = async () => {
    const data = await fetch('/api/data');
    setData(data);
  };
  fetchData();
}, []);
\`\`\`

Understanding the dependency array is key to avoiding infinite loops and stale closures.

### Custom Hooks

Custom hooks are where the real magic happens. They allow you to extract component logic into reusable functions.

For example, a \`useWindowSize\` hook can be used across multiple components to make them responsive.

## Conclusion

Hooks make our code more readable, reusable, and easier to test. If you haven't fully embraced them yet, now is the time.
    `,
    publishedAt: "2025-11-02",
    readingTime: "5 min read",
    tags: ["React", "JavaScript", "Coding"],
    coverImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "3",
    slug: "the-future-of-ai-in-coding",
    title: "The Future of AI in Coding",
    summary: "How AI tools like Copilot and ChatGPT are changing the landscape of software engineering.",
    content: `
## AI as a Pair Programmer

Artificial Intelligence is transforming every industry, and software development is no exception. Tools like GitHub Copilot act as an intelligent pair programmer, suggesting code snippets and even entire functions.

### Productivity Boost

For boilerplate code and repetitive tasks, AI is a game-changer. It frees up developers to focus on complex architectural decisions and business logic rather than syntax.

### The Human Element

However, AI is not a replacement for human engineers. It lacks the context, creativity, and deep understanding of the problem domain that a human brings. Code generated by AI still needs to be reviewed, tested, and understood.

## Ethical Considerations

There are also valid concerns about copyright, security, and the potential for AI to hallucinate incorrect code. As we integrate these tools, we must remain vigilant.

### Final Thoughts

AI is a powerful tool in our arsenal. By embracing it responsibly, we can become more efficient and effective developers.
    `,
    publishedAt: "2025-12-10",
    readingTime: "4 min read",
    tags: ["AI", "Technology", "Future"],
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1000&auto=format&fit=crop",
  },
];

export function getAllPosts(): BlogPost[] {
  return BLOG_POSTS.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((post) => post.slug === slug);
}
